(()=>{if(window.__bourgEquipmentVisualsV2)return;window.__bourgEquipmentVisualsV2=true;
const ASSETS={inline:'./inline-config.jpg',offline:'./offline-config.jpg'};
const css=`.config-visual{margin:0 0 16px;border:1px solid var(--line);border-radius:16px;background:#fff;overflow:hidden}.config-visual img{display:block;width:100%;height:auto;max-height:260px;object-fit:contain;background:#fff}.config-caption{padding:9px 11px;border-top:1px solid var(--line);font-size:11px;line-height:1.4;color:var(--muted)}.config-caption b{color:var(--navy)}.machine-visual{display:block;width:100%;height:118px;object-fit:contain;background:#fff;border:1px solid #edf2f5;border-radius:12px;margin:0 0 10px}.visual-tag{display:inline-flex;align-items:center;gap:5px;font-size:10px;font-weight:850;color:var(--navy);background:#edf5fa;border-radius:999px;padding:4px 7px;margin-bottom:8px}@media(max-width:520px){.config-visual img{max-height:190px}.machine-visual{height:96px}}`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
function fullVisual(id,src,alt,title,caption,target){if(document.getElementById(id)||!target)return;const fig=document.createElement('figure');fig.id=id;fig.className='config-visual';const img=document.createElement('img');img.src=src;img.alt=alt;img.loading='eager';img.decoding='async';const cap=document.createElement('figcaption');cap.className='config-caption';cap.innerHTML=`<b>${title}</b> — ${caption}`;fig.append(img,cap);target.before(fig)}
fullVisual('inlineEquipmentVisual',ASSETS.inline,'Inline CP Bourg BBM/BMe configuration connected directly to a printer','Inline configuration','Printer feeding directly into the CP Bourg BBM/BMe finishing line.',document.getElementById('inlineInputs'));
fullVisual('offlineEquipmentVisual',ASSETS.offline,'Offline CP Bourg configuration with BSF, BPM and BBM/BMe','Offline configuration','Bourg Sheet Feeder (BSF) → Bourg Preparation Module (BPM) → BBM/BMe.',document.getElementById('offlineInputs'));
function enhanceCompare(){const root=document.getElementById('compareResults');if(!root)return;const add=(selector,src,label,alt)=>{const card=root.querySelector(selector);if(!card||card.querySelector('.machine-visual'))return;const head=card.querySelector('.machine-head');if(!head)return;const tag=document.createElement('div');tag.className='visual-tag';tag.textContent=label;const img=document.createElement('img');img.className='machine-visual';img.src=src;img.alt=alt;img.loading='eager';img.decoding='async';head.after(tag,img)};add('.machine.inline',ASSETS.inline,'Inline configuration','Inline CP Bourg BBM/BMe configuration connected to a printer');add('.machine.offline',ASSETS.offline,'BSF → BPM → BBM/BMe','Offline CP Bourg configuration with BSF, BPM and BBM/BMe')}
enhanceCompare();const root=document.getElementById('compareResults');if(root)new MutationObserver(enhanceCompare).observe(root,{childList:true,subtree:true});
})();